### ISSUE TITLE
create "security overview" dashboard in kibana

### ISSUE THREAD

**Issue by mmguero** [cisagov/Malcolm#108]
I'm going to create a dashboard for Kibana that is more security oriented. While a lot of the other dashboards are more an overview of whatever type of traffic you have, this will contain things which may be a security concern, such as:

- a high-level summary of the zeek "notice" categories
- any triggered signatures (like from clamav, virustotal, etc.)
- protocol and username associated with any clear-text transmission of passwords detected
- protocols using outdated versions with known vulnerabilties, which for now i have defined as
  - ssh < 2
  - smb < 2
  - tls < 1.2
  - ntp < 4
  - rfb/vnc < 3.8
  - rdp < 6.0
  - snmp < 3
  - all uses of FTP
- a region map of outbound connections by country
- a table of internal source/external destination connections by country
- a table of external source/internal destination connections by country
- a list of the file types seen transferred over the network
- a date/time histogram visualizing "remote access protocols" to/from external hosts
  - zeek.service:(ssh OR rdp OR rfb)
  - tags:(external_source OR external_destination)
- DNS queries ordered by entropy/randomness
  - see issue #107 
  - uses [freq.py](https://github.com/MarkBaggett/freq)
  - for detecting DGA malware, could be used for other stuff in the future

Still todo/ideas:
- more protocols for "insecure protocols" list
  - telnet/rsh/rlogin

- more uses of [freq.py](https://github.com/MarkBaggett/freq) (issue #107)?
  - filenames
  - TLS certificate subjects
  - other hostnames (although DNS should pretty much see them all first)

I will be creating issue #109 to create a similar dashboard specifically for ICS networks.

**Comment by ruffy91** [comment]
How can we add these kibana dashboards to existing/ugraded installations of malcolm?

**Comment by mmguero** [comment]
> How can we add these kibana dashboards to existing/ugraded installations of malcolm?

Yeah, upgrades are something I need to figure out a standardized way to do. The sure-fire way to get the new kibana dashboards after upgrading to the newest Malcolm docker images is to delete the old kibana index pattern. The cron job that checks every few minutes to see if it exists will detect it's missing and re-create it, as well as import/re-import all of the dashboards.

To do this, go to Kibana, click the Management ⚙ icon in the navigation panel, click Index Patterns, click, `sessions2-*`, then click the Trash 🗑 icon. It will prompt "Delete index pattern?" so choose Delete. Then after a few minutes you should see in the debug output that Kibana is re-importing the dashboards.
