### ISSUE TITLE
MANAGE_PCAP_FILES not working

### ISSUE THREAD

**Issue by ruffy91** [cisagov/Malcolm#114]
I set MANAGE_PCAP_FILES to true but PCAP Files just fill the disk and packets stop being captured.
The documentation says:
MANAGE_PCAP_FILES – if set to true, all PCAP files imported into Malcolm will be marked as available for deletion by Moloch if available storage space becomes too low (default false)

Does moloch have to be configured too for this?

**Comment by mmguero** [comment]
I'm not at my computer at the moment, but if you go under the "stats" tab and then to "files" are the PCAP files showing locked as true or false?

I'm out of the office tomorrow but I can look Monday when I'm back and see if I can point you in the right direction.

**Comment by ruffy91** [comment]
They show as not locked (locked = false).
![image](https://user-images.githubusercontent.com/344634/76209914-5349f080-6203-11ea-8494-440bab48044d.png)

**Comment by mmguero** [comment]
Sorry I haven't been able to look at this, things have been kind of crazy for the whole world.

[Here's something](https://molo.ch/faq#pcap-deletion) you could read about. Moloch viewer is what should be handling it. I will get to looking at it before the v2.0.0 release though, I promise.

**Comment by mmguero** [comment]
I was able to reproduce the problem, my malcolm's config.ini is misconfigured. I'll put in a fix for it

**Comment by mmguero** [comment]
Will be fixed in 2.0.0 release coming out in the next couple of weeks. If you wanted to locally patch, apply the changes from commit b4b6586 to your config.ini file and rebuild the moloch image (`./scripts/build.sh docker-compose.yml moloch`). Thanks for the bug report
