### ISSUE TITLE
Is that possible to decrypt the ssl/tcp for http protocol?

### ISSUE THREAD

**Issue by Wapiti08** [cisagov/Malcolm#115]
I just found the Zeek can be used to segregate the network packages into logs, like http.log, ssl.log, and x509.log. 

While I want to analyze the https.log, which I can see the request with the full URL, not only the server name.

Is there any way to achieve that? or provided by the Malcolm?

**Comment by mmguero** [comment]
No, Malcolm is not a tool that does SSL decryption. Malcolm can give you non-encrypted DNS requests, SSL certificate and handshake information, but not full URLs or content of encrypted sessions.

**Comment by Wapiti08** [comment]
thanks. Got that!




| |
tzrzhuoran
邮箱：tzrzhuoran@163.com
|

Signature is customized by Netease Mail Master

On 03/15/2020 05:28, SG wrote:

Closed #115.
