### ISSUE TITLE
Kibana ElastAlert rule editor does not work with Kibana 7.6.0

### ISSUE THREAD

**Issue by mmguero** [cisagov/Malcolm#119]
Because of this change in Kibana ("Route payload must be set to 'parse' when payload validation enabled" https://github.com/elastic/kibana/issues/57777), the elastalert kibana plugin is incompatible with Kibana 7.6.0 (https://github.com/bitsensor/elastalert-kibana-plugin/issues/141).

ElastAlert still works, it's just that until we get this fixed rules will have to be edited externally via a text editor rather than via Kibana.

As of now this is the only thing holding up Malcolm 2.0.0. I may end up releasing that anyway even with this bug outstanding.

**Comment by mosajjal** [comment]
I think this might also tie together with #70 since OpenDistro's Kibana Alerting covers what ElastAlert is offering (IMO)

**Comment by mmguero** [comment]
Fixed via https://github.com/idaholab/Malcolm/commit/b38ddb7f0d4c5b03e6f8ccad58a656644e113b19#diff-74f6f33f6838eb7b6c032ba52d66684f

Thanks to https://github.com/elastic/kibana/issues/57777#issuecomment-608516900
