### ISSUE TITLE
filebeat can get into a state where it's doing 100% CPU when "idle"

### ISSUE THREAD

**Issue by mmguero** [cisagov/Malcolm#13]
Not sure how this happens yet, but occasionally fter a lot of pcap uploads filebeat can get into a state where it's doing 100% CPU when "idle".

Not 100% reproducible, but I would like to figure it out.

**Comment by vardhasu** [comment]
I think there is a conf setting for this. I ran into this couple of years back and I think I sent a filebeat conf.

**Comment by vardhasu** [comment]
Try to set max_procs:2 in filebeat.yml

**Comment by mmguero** [comment]
Great, I will try that the next time I am looking at this. Thank you!

**Comment by mmguero** [comment]
Have not seen this in a while, closing.
