### ISSUE TITLE
Zeek Intel Framework

### ISSUE THREAD

**Issue by cyamal1b4** [cisagov/Malcolm#131]
Greetings, so I've been up and down in the docs for Zeek and understand decently well how to create Intel in Zeek, however, that is largely aligned with a normal deployment of Zeek. I have loaded the required policies and pointed zeek (in local.zeek) to my local bro formatted file with an indicator. I tested everything in the TryZeek page with the same pcap, local.zeek changes, as well as the same bro intel file. However, when I replicate I cannot get Malcolm (under the Kibana-Zeek Intel or Notice dashboards) to pick up on my Intel hit. I have noticed some differences in the deployment with Malcolm so I figured it would be best to ask the developer directly. Thanks for your support and contribution!!

**Comment by mmguero** [comment]
I haven't really done anything with the intel framework in Malcolm yet, but I can give you a little bit of advice on how local.zeek gets loaded in Malcolm.

The `./zeek/config/local.zeek` file gets built into the `malcolmnetsec/zeek` package, but it can be overriden with a docker volume mount. Depending on which `docker-compose` file you're using (`docker-compose.yml` which is more for development and has a lot of local files volume-mounted into the docker container, or `docker-compose-standalone.yml` which is what you get for `docker-compose.yml` if you grab it from the Releases artifacts) this may or may not already be happening, but you can check in by looking for the `zeek:` service in your `docker-compose.yml` file.

If you see a line in the `volumes:` section under `zeek:` that looks like this:

```
- ./zeek/config/local.zeek:/opt/zeek/share/zeek/site/local.zeek:ro
```

Then you should be getting your local modifications to `local.zeek` when you run Malcolm. If you don't, you could try adding that to the `volumes:` section for `zeek:` and see if you get different results.

If you still aren't seeing things, check under `./zeek-logs` after importing your PCAP and see if the intel file is getting created.

```
# find ./zeek-logs -type f -name "intel*"
```

Perhaps it is getting created, but I've got an issue parsing the file?

**Comment by cyamal1b4** [comment]
So here is my local.zeek that is a volume on the host for the containers related file. I added the Intel::read_files as well as the 2 policies related to Intel as well below. 

#! Zeek local site policy. Customize as appropriate.
##!
##! See https://github.com/zeek/zeekctl
##!     https://docs.zeek.org/en/stable/script-reference/scripts.html
##!     https://github.com/zeek/zeek/blob/master/scripts/site/local.zeek

redef Broker::default_listen_address = "127.0.0.1";
redef ignore_checksums = T;
redef HTTP::default_capture_password = T;
redef FTP::default_capture_password = T;
redef SOCKS::default_capture_password = T;
redef Intel::read_files += { "/home/sansforensics/Downloads/BroStuff.txt" };

@load tuning/defaults
@load misc/scan
@load frameworks/software/vulnerable
@load frameworks/software/version-changes
@load frameworks/software/windows-version-detection
@load-sigs frameworks/signatures/detect-windows-shells
@load protocols/conn/known-hosts
@load protocols/conn/known-services
@load protocols/dhcp/software
@load protocols/dns/detect-external-names
@load protocols/ftp/detect
@load protocols/ftp/detect-bruteforcing.zeek
@load protocols/ftp/software
@load protocols/http/detect-sqli
@load protocols/http/detect-webapps
@load protocols/http/software
@load protocols/http/software-browser-plugins
@load protocols/mysql/software
@load protocols/ssl/weak-keys
@load protocols/smb/log-cmds
@load protocols/smtp/software
@load protocols/ssh/detect-bruteforcing
@load protocols/ssh/geo-data
@load protocols/ssh/interesting-hostnames
@load protocols/ssh/software
@load protocols/ssl/known-certs
@load protocols/ssl/log-hostcerts-only
@load protocols/ssl/validate-certs
@load tuning/track-all-assets.zeek
@load frameworks/files/hash-all-files
@load policy/protocols/conn/vlan-logging
@load policy/protocols/conn/mac-logging
@load policy/protocols/modbus/track-memmap
@load policy/protocols/modbus/known-masters-slaves
@load policy/protocols/mqtt
@load policy/frameworks/intel/seen
@load policy/integration/collective-intel
@load policy/frameworks/intel/do_notice
--@load frameworks/files/detect-MHR

--custom packages installed manually
@load Corelight/PE_XOR
@load Salesforce/GQUIC
@load ./bzar
--custom packages managed by zkg via packages/packages.zeek
@load ./packages/packages.zeek
--and apparently some installed packages (BRO::LDAP) are loaded automatically

Here is the BroStuff.txt file generated from cifv5 that supposedly puts it into the correct bro tab separated format. 

#fields	indicator	indicator_type	meta.desc	meta.confidence	meta.source	meta.do_notice
23.15.54.44	Intel::ADDR	proxy|tor	4	check.torproject.org	T

That IP (23.15.54.44) is in my instance from a malicious pcap I have. However as a test its not actually on that list as malicious in the wild.

I checked in the logs and it isn't creating the intel log file. Either. I feel its a parsing issue as well but not sure yet.

**Comment by cyamal1b4** [comment]
I did look in the reporter log and see it appears to have an issue with the formatting of the file. I’ll dig into that and update. This is what I get as an error in the reporter log: 
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   reporter
#open   2020-05-21-20-49-55
#fields ts      level   message location
#types  time    enum    string  string
1590094195.785510       Reporter::WARNING       /opt/zeek/share/zeek/site/opt/intel-stack-client/frameworks/intel/master-public.dat/Input::READER_ASCII: Init: cannot open /opt/zeek/share/zeek/site/opt/intel-stack-client/frameworks/intel/master-public.dat     (empty)
#close  2020-05-21-20-49-57

I did change the file from BroStuff.txt to master.... that is referenced above ^

**Comment by cyamal1b4** [comment]
@mmguero figured it out. It was just a docker-ism. Just needed an additional mapping for the intel file as a volume into the container. For reference I am using intel generated by intelstack's client that natively gets it into TSV format. Do you know off hand if Malcolm would support a tune to JSON or would that disturb other modifications? Thanks brother!

**Comment by mmguero** [comment]
If you're talking about the various Zeek .log files themselves, currently just the delimited format is supported as that's how the [Logstash filters parsing them](https://github.com/idaholab/Malcolm/blob/master/logstash/pipelines/zeek/11_zeek_logs.conf#L93) are expecting them.

Glad you figured it out.

For now I'll leave this issue open and maybe see about making mapping zeek intel files into the containers more automatic as an enhancement.

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [idaholab/Malcolm](https://github.com/idaholab/Malcolm/issues/20)
