### ISSUE TITLE
Install quik start and example conflict/unclear

### ISSUE THREAD

**Issue by schallee** [cisagov/Malcolm#136]
Greetings, thanks for all your hard work on this!

I am trying to install on a vm today and am running into problems. I'm going to try to put issues in where I can. My vm is a minimal amd64 debian buster. I am going the git clone docker-compose pull route. I'm not sure exactly what is causing the issues I am seeing so I'm going back and verifying my steps before continuing. In doing so I thought it might be useful to comment on some confusion of mine in the documentation. Most of this is likely minor. It is worth noting that, although chroot jails and vms are not new to me, this is my first real exposure to docker.

The quick start's installation order is not procedural. After example output from `docker-compose pull` it says the following:

> You must run auth_setup prior to running docker-compose pull. You should also ensure your system configuration and docker-compose.yml settings are tuned by running ./scripts/install.py or ./scripts/install.py --configure (see System configuration and tuning).

It would be better to put this before the `pull`.

The order in the quick start would seem to be:

1. `git clone`
2. `auth_setup`
3. `install.py` _or_ `install.py --configure`
4. `docker-compose pull`
5. `./scripts/start`

The order in the example seems to be:

1. `git clone`
2. `sudo python3 ./scripts/install.py`
3. `python3 ./scripts/install.py --configure`
4. `reboot`
5. `auth_setup`
6. `docker-compose pull`
7. `./scripts/start`

The quick start doesn't mention which user to run the commands as so I would assume it is root. The example is more clear but the relationship between the installing unprivileged user being the same as the user specified for the docker group could be tightened.

The example ubuntu has both `./scripts/install.py` and `./scripts/install.py --configure`. The quick start should probably explain what should be run for `git clone` vs. a tarball. Similarly "or" should probably be "and/or".

The version of python is not specified (the which version/install dir on which distro/os/pkg manager is maddening and contributes to my continued use of perl). The quick start just says to run `install.py` which uses the first `python` in the path. The example specifically uses python3. At least on the current debian stable (buster) the default `python` is 2.7. I'm not sure what ubuntu's default is. I'm not seeing any warnings/errors running it with python 2 at least but I'm guessing it should be run with python3.

The quick start doesn't directly state a reboot. Is the install just adding to /etc/sysctl.conf (fyi: it might be worth considering a separate file in /etc/sysctl.d if it exists)? I would have expected it to both add them and apply them (sysctl -p) making much of the purpose of the reboot mute (I don't know how/when systemd/docker notices the changes to limits.conf so a reboot may still be best in a quick start).

Thanks again for all your hard work. Hopefully this is helpful to you;)

**Comment by mmguero** [comment]
Thanks, I really appreciate it, this is valuable feedback. I'll go through and make clarifications for all of these and comment with the commit SHA here as soon as I get a chance.
