### ISSUE TITLE
Investigate additional scanners

### ISSUE THREAD

**Issue by mmguero** [cisagov/Malcolm#14]
Investigate integrating other scanners into Malcolm:

- yara
- rita
- snort
- packetbeat
- suricata

If/when I decide to move on any of these, I'll log a separate issue.

**Comment by nilssachs** [comment]
Adding a signature based scanner would be awesome. Found this to be very helpful for giving more context to alarms.

**Comment by mmguero** [comment]
[capa](https://github.com/fireeye/capa) looks interesting for exe analysis

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [idaholab/Malcolm](https://github.com/idaholab/Malcolm/issues/7)

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [idaholab/Malcolm](https://github.com/idaholab/Malcolm/issues/8)
