### ISSUE TITLE
Cant view elastalert debug alerts

### ISSUE THREAD

**Issue by yagely80** [cisagov/Malcolm#140]
Ive tried to use the debug alerter, but i cant figure out where can i view these alerts.. they do not appear in the console in which malcolm is dumping all the logs

**Comment by mmguero** [comment]
Thanks for the report, I'll check it out this next week and get back to you.

**Comment by mmguero** [comment]
One question, is your traffic "live" traffic (being captured "now"-ish by Malcolm) or are these historical PCAPs you're uploading? I'm seeing my alerts okay when I do debugging.

In my test rule file I've got `alert_text_type: alert_text_only`, and `alert_text` and `alert_text_args` set. Then periodically I see:

```
elastalert_1     | 12:53:34.259Z  INFO elastalert-server:
elastalert_1     |     ProcessController:  Network traffic captured by filebeat generated a dns log for ['dns'] traffic with action ['INTERNET A']: "['Success']"
```

Depending on what your `alert_text` is.

You could try resetting the elastalert database and see if that helps, by running this in the Malcolm directory:

```
docker-compose stop elastalert; docker-compose exec -T -u curator curator curl -sSL -X DELETE "elasticsearch:9200/elastalert*?pretty" ; docker-compose restart elastalert
```

**Comment by yagely80** [comment]
my traffic is composed of "historical" PCAPS, could it be that i configured the time that elastalert looks backwards wrong?
how do i configure it correctly? 
ill also try to change the alert text rules - 
thanks for the help.

**Comment by mmguero** [comment]
Hmm, yeah I wonder if that is the problem. I've only used Elastalert for live traffic, but I don't know how it works with events that are coming in "out of order" or with an older time frame. That might be a shortcoming of that tool. I will try to get some time to do some more research on that. Sorry I don't have a more ready answer for you.

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [idaholab/Malcolm](https://github.com/idaholab/Malcolm/issues/21)
