### ISSUE TITLE
Check for root user depends on sudo specifics

### ISSUE THREAD

**Issue by schallee** [cisagov/Malcolm#142]
The check depends on sudo specific environmental variables. If sudo was used from root or another user to the user that is to run malcolm the start script will fail complaining that it should not be run as root.

This test would also fail if 'su' or another method of becoming root were used.

On *nix this should be a check of what getuid and geteuid returns. I've submitted a pull request with this change and, once I remember how, I'll link the issue and pull request.

**Comment by schallee** [comment]
PR #141

**Comment by mmguero** [comment]
Merged #141

**Comment by schallee** [comment]
Thanks. It looks like it is running for me. Now I just have to learn how to use it;)

**Comment by mmguero** [comment]
Ha! Thanks for your input and help on this one.
