### ISSUE TITLE
Extend ICS Capabilities

### ISSUE THREAD

**Issue by timyardley** [cisagov/Malcolm#144]
Malcom Team,

The following add-ons may be useful to you in analyzing ICS protocols in Malcolm:

[ARMORE "Bro" Scripts](https://github.com/ITI/ARMORE/tree/master/source/bro/scripts)

[Second Generation](https://github.com/ITI/EDMAND)

[Third Generation](https://github.com/ITI/aius)

Happy to elaborate on these if it isn't clear from the code.

Tim

**Comment by mmguero** [comment]
Thank you very much! I will check these out.

**Comment by timyardley** [comment]
No problem. Let me know if you have any questions on the work. Mostly bro scripts.

There are a bunch of other items that might make sense to include in your images. Do you want separate issues for each of them?

**Comment by mmguero** [comment]
Absolutely, if you're willing. I can't guarantee prioritization of my own work for any particular item beyond what my funding source is prioritizing, but I would welcome ideas for improvements and enhancements.

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [idaholab/Malcolm](https://github.com/idaholab/Malcolm/issues/22)
