### ISSUE TITLE
Dependency failure between services and settings (htadmin/freq/nginx-proxy)

### ISSUE THREAD

**Issue by gentoo9ball** [cisagov/Malcolm#162]
When:
 FREQ_LOOKUP is false
and/or
  NGINX_BASIC_AUTH is false

supervisord settings prevent these (freq and htadmin) services from starting, hence they remain unhealthy and `./scripts/start` never returns

So in an effort to circumvent this, I removed things (freq and htadmin as well as the htadmin dependency from nginx-proxy) from the docker-compose file and found another dependency that fails. nginx-proxy references htadmin:80 and therefore never will become healthy since in my circumvention htadmin doesn't exist anymore.

**Comment by mmguero** [comment]
Thanks, I'll take a look.

**Comment by mmguero** [comment]
Will be fixed in v3.0.2 release.
