### ISSUE TITLE
Installation doesn't work anymore (old title:auth_setup docker not found)

### ISSUE THREAD

**Issue by Thomislav** [cisagov/Malcolm#166]
Hi, when i execute the auth_setup script it says docker not found execute install.py even when docker is installed.
I tested commenting out the lines 830-838 of auth_setup and then it worked. First time using Github so i hope this is the right place for it.

Edit: the script is running but not working, seems like Docker-Compose is not found 
![image](https://user-images.githubusercontent.com/84561792/119128520-0d5b0000-ba36-11eb-9ef1-48fa5a8761fa.png)
i tried removing it and installing in different ways. Installed it a week or two ago and it worked. Tried different Machines.

**Comment by Thomislav** [comment]
I found a Workaround that i perform before starting any of the malcolm scripts:
sudo apt-get update -y && sudo apt-get install -y python3-pip python3-dev
sudo apt-get remove docker docker-engine docker.io
curl -fsSL get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo pip3 install docker-compose
sudo usermod -a -G docker $USER

I don't know where the exact Problem is, if its a problem with the online repository and not the Malcolm files you can delete this issue

**Comment by Thomislav** [comment]
Since the Problems carry on i changed the Title. Next Problem is the start script doesn't work. i tried starting it with sh -x to see where the problem is and it says in line 20 "syntax error: "(" unexpected
It worked like two weeks ago and i don't know if the problem is with Malcolm Repository or Ubuntu im using, but i can't see anything that would cause these problems. i hope someone can help.

**Comment by mmguero** [comment]
The control script (which includes auth_setup, start, etc.) were changed from bash to python 3 some time ago. So running `sh -x start` or something like that wouldn't work.

Let's verify a couple of things, can you run `docker info` and `docker-compose --version` as the regular (non-root) user and not get an error?

Next, try running `auth_setup` or `start` with the `-v` flag to get verbose output and let's see what it's failing on.

**Comment by Thomislav** [comment]
Running it with bash was just to test where it gets stuck but maybe that was wrong or misleading to myself. But the first time i installed Malcolm (2-3 weeks ago) i didnt use bash just the lines from the documentation and it worked. I used the administrative user that i added while installing ubuntu. While installing i used the sudo command when the documentation said to use it.

I addes a non-root user and tried the two commands you wrote:
![IMG-1683](https://user-images.githubusercontent.com/84561792/119370771-f3c7eb80-bcb5-11eb-9998-a553922e1da4.JPG)

After that i tried the -v flag for start script
![IMG-1684](https://user-images.githubusercontent.com/84561792/119370784-f75b7280-bcb5-11eb-8d5b-365e70d84821.JPG)
It just stays like that

**Comment by mmguero** [comment]
Hmm, that's odd that `docker info` returns `permission denied` when run in your first screenshot, but the same `docker info` command doesn't return an error in the debug output on the second screenshot.

You're sure that in both screenshots things are being run by the same account (no `sudo` involved anywhere)?

One thing that's weird about the screenshots to me, although maybe you've just got custom config or something: in the screenshot the username is `analyst` and the home directory seems to be `/home/auto`. This isn't impossible, of course, as you can set the home directory for a user to whatever you want, but usually the home directory for `analyst` will be `/home/analyst` so just make sure that all matches. 

We could check permissions on files. Do `./scripts/stop` then, in the malcolm directory, `sudo chown -R analyst:analyst /home/auto/Malcolm`. I assume the UID and GID values in the top of your docker-compose file also match your user ID as you intend.

**Comment by Thomislav** [comment]
Ok, my mistake. in the second screenshot i changed back to the auto user since the Malcolm Data is in the /home/auto path.
When i copy the data from github through git clone it automatically copies it to /home/auto/Malcolm. But again, when it worked i also just used the auto user.

**Comment by mmguero** [comment]
`git` will clone the data wherever you tell it to clone it... it doesn't automatically copy it anywhere.

I think this probably still has something to do with file permissions. I assume you're at the latest Malcolm code (currently the head of `master` or the v3.1.0 release)? There was a previous bug where when generating some `.keystore` files would not work correctly if you're running malcolm as a non-default (non UID 1000) user.

You could check to see if that's the case. Inside the Malcolm directory

- `./scripts/stop`
- `sudo chown -R $(id -u):$(id -u) *`
- `rm -rf ./elasticsearch/elasticsearch.keystore ./logstash/certs/logstash.keystore`

Then try the startup again. Again, please make sure you're at the latest version of the code first.

**Comment by Thomislav** [comment]
Ok, i used the newest code, i tried the code you posted and used a non-root user, didnt work. 
After that i even installed a new VM for a clean start and at the end i ended with the same Problem i started with:
![image](https://user-images.githubusercontent.com/84561792/119637013-7e732c80-be15-11eb-8cd0-69b915122a4f.png)
the script auth_setup can't use docker/docker-compose

**Comment by mmguero** [comment]
In this case the error is evident, your user (`auto`) cannot connect to the docker socket. Either 1) `auto` is not a member of the `docker` group, or 2) you've added `auto` to the `docker` group but you need to log out and log back in for the new group membership to take effect.

If you can't run `docker info` as `auto` from the command line, none of the Malcolm stuff will work.

Perhaps the pre-configured [ISO file](https://malcolm.fyi/download/) would be easier for you to get set up? This [video](https://www.youtube.com/watch?v=q0H5jmQz8iA) might help you with that, too.

**Comment by Thomislav** [comment]
Thank you for your help. Whith your help i found a way to install it. Here's what i did:
The author of the video you linked has another one where he installs it in a different way.
I downloaded the install.py and malcolm_xxxxxxx.tar.gz files and ran the install.py script.
After that docker and docker-compose worked both. Docker-compose pull worked and auth_setup script worked.

I don't know what the difference between that and git clone is but somehow one way worked and one didn't
