### ISSUE TITLE
error building ISO with nested virtualization (virtualbox inside VMWare)

### ISSUE THREAD

**Issue by colt-cmd** [cisagov/Malcolm#167]
# 🐛 Summary #
I currently have Malcolm installed on RHEL 8.4 and I'm trying to run the script to make a Malcolm.iso file. I have Vagrant and VirtualBox installed. Whenever I run the ./malcolm-iso/build_via_vagrant.sh -f script I get an connection to 127,0.0.1 closed by remote host along with all the CPUs saying stuck.

![image](https://user-images.githubusercontent.com/54329941/119747135-11d14f80-be60-11eb-95ed-245784e490a2.png)

**Comment by mmguero** [comment]
Interesting, that's not one I've run into before. Just googling the "watchdog bug soft lockup" error message, trying to see what might be going on. Are you doing nested virtual machines (i.e., running this build environment itself inside a VM)? I don't have an answer for you at the moment but the general feeling I'm getting from forum posts about that error message is that it seems to be a virtualbox bug. What version of virtualbox are you running?

I'm not where I have the equiptment to try to set up a rhel build environment. I know this isn't a solution, but if your end goal is to get a Malcolm VM you're welcome to download the "unofficial" build I've got hosted elsewhere at [malcolm.fyi](https://malcolm.fyi/download/).

**Comment by colt-cmd** [comment]
The version of Virtual box that I'm using is version 6.1.22 r144080. I have RHEL 8.4 as a VM on VMware Workstation and then have virtual box installed on the VM along with Vagrant.

**Comment by mmguero** [comment]
moved to idaholab/Malcolm#45
