### ISSUE TITLE
Very large pcaps don't get proccesed

### ISSUE THREAD

**Issue by cryptonightly** [cisagov/Malcolm#168]
# 🐛 Summary #

When placing a large pcap (50GB +) in the Malcolm upload folder it doesn't seem to get processed. Testing the same procedure with a 1GB pcap works just fine.

## To reproduce ##

1. Place a large pcap in the 'upload' folder. (Copy or via SFTP)
2. The process pcap-monitor_1 renames (moves) the pcap to the 'processed' folder
3. Nothing happens... elasticsearch_1 doesn't create or updates the index. No zeek logs created either. Size of elasticsearch index stays the same.

## Expected behavior ##

Creating or updating the index, creation of Zeek logs, etc.

**Comment by mmguero** [comment]
Thanks for the report.

**Comment by mmguero** [comment]
moved to idaholab/Malcolm#44
