### ISSUE TITLE
LDAP Bind credentials world readable in docker

### ISSUE THREAD

**Issue by gentoo9ball** [cisagov/Malcolm#171]
# 🐛 Summary #

What's wrong? Please be specific.
LDAP Bind credentials in this file are readable by anyone. Can we put some permissions on the file when it gets created in the nginx entrypoint?

-rw-r--r-- /var/lib/docker/overlay2/*****/diff/etc/nginx/nginx_ldap_rt.conf

## To reproduce ##

1. Standard build with LDAP
1. Grep overlay2 for bind credentials

## Expected behavior ##
Readable only by user running nginx

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by mmguero** [comment]
Thanks for the report, I'll take a look at it. The one question I have for you: how is the world reading `/var/lib/docker/...`? Every docker installation I've ever seen has privileges `/var/lib/docker/` itself locked down.

```
user@host ~ › ls -l /var/lib/docker/
ls: cannot open directory '/var/lib/docker/': Permission denied
user@host ~ › grep -R bind /var/lib/docker/
grep: /var/lib/docker/: Permission denied
```

**Comment by mmguero** [comment]
Either way, I've pushed a fix up to a development branch that will be merged in here when I do the next release (in the next week or so). See 02e8f53 if you want the details of the patch for your local instance before that.

**Comment by mmguero** [comment]
Moved to idaholab/Malcolm#47.

**Comment by gentoo9ball** [comment]
@mmguero Thanks! I think it depends how you install docker, but that's an interesting note. Appreciate the push
