### ISSUE TITLE
Issue with auth_setup, says I need docker installed but it already is

### ISSUE THREAD

**Issue by Jallnutt1** [cisagov/Malcolm#184]
# 🐛 Summary #

What's wrong? I am trying to install Malcolm on my Ubuntu machine. I got through the install.py and install.py --configure. However, when I got to running the auth_setup script I get "Exception: auth_setup requires docker, please run install.py". I ran install.py but nothing really happens. Everything else in the install was going smoothly. I also tried "sudo ./auth_setup", but that just presented another exception that says I shouldn't run that script as root. 

## To reproduce ##

Run the install script and then run the install script again, then run the auth_setup script. 

## Expected behavior ##

I did not expect to get an exception. 

## Any helpful log output or screenshots ##

Paste the results here: n/a

```console

```

Add any screenshots of the problem here.
![Screenshot from 2022-01-17 22-22-03](https://user-images.githubusercontent.com/30048057/149865398-85c20baf-ef0d-4c88-873a-004eb3738268.png)

**Comment by mmguero** [comment]
try running `./auth_setup -v` and it should print out a bunch of debug information I can look at.

**Comment by mmguero** [comment]
Also, you can try what the script is doing, which is essentially running `docker info` and checking the exit code.

```
> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
...
> echo $?
0
```

**Comment by Jallnutt1** [comment]
Thank for the response. I tried `./auth_setup -v'`the other day and had success running the script. However, Malcolm would not then start when running the start command. I decided to reinstall Ubuntu and try the whole process over again. I tried to capture my output from running `./auth_setup`, `auth_setup -v`, `docker info`, and some other commands. in the file attached. I also provided a screen shot. Please let me know if I can gather any other information. 

[malcolm-install-output-files.tar.gz](https://github.com/cisagov/Malcolm/files/7917456/malcolm-install-output-files.tar.gz)

**Comment by mmguero** [comment]
```
Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
```

That's the root of your error. Check to make sure your user is in the `docker` group (by running `id`) and if not, add it (`sudo usermod -a -G docker jdoe`).

Alternately, if you want to just install the ISO with docker already set up, you can get it [here](https://malcolm.fyi/download/).

**Comment by mmguero** [comment]
@Jallnutt1 if you're still tracking this let me know, otherwise i'll close it.

**Comment by nzdev03** [comment]
If the above solution @mmguero provided still yields no positive results try:

Adding the docker group:
```
sudo groupadd docker
```

Next add the current user to the docker group:
```
sudo usermod -aG docker $USER
```

Next log out and log back in, **NOTE**: this doesn't mean exit your terminal and reopen a new one. Literally log out of your current user session using your desktop environment's user panel/log out feature. Re-login and everything should be working soundly after.

**Comment by ee-hex-ee** [comment]
I was aware of the user group aspect of this, but after a fresh Ubuntu 22 install and git clone, I too am running into this same issue with no fix. 

docker -v 
`Docker version 28.1.1, build 4eba377`

./scripts/auth_setup -v

![Image](https://github.com/user-attachments/assets/e2354035-82e9-4a43-b0bd-66a8e921f2e5)

**Comment by mmguero** [comment]
Look at your [`./config/process.env`](https://github.com/idaholab/Malcolm/blob/main/config/process.env.example)

from that error message, it looks to me like [these two lines](https://github.com/idaholab/Malcolm/blob/33df9210723608a28569b138e4745c773757c75b/config/process.env.example#L9-L10) somehow got smooshed together. Put the comment on its own next line and you should be good.
