### ISSUE TITLE
Problem running behind Proxy

### ISSUE THREAD

**Issue by RafnexJr** [cisagov/Malcolm#203]
# 🐛 Summary #

While installing Malcolm in an environment running behind a proxy problems with the Arkime container occured. The script `initarkime.sh` tries to download/update the geo data but fails behind a proxy. Even when the proxy is configured as environment variable in the `docker-compose` file. There's no error message the script just won't return anything after line 11.

## To reproduce ##

1. Install according to documentation
2. Set proxy environment variables `HTTP_PROXY` and `HTTPS_PROXY` on the `file-monitor` and `arkime` container
3. Start Malcolm with the script

## Expected behavior ##

I would expect that the container would use the proxy specified in the `HTTP(S)_PROXY` env variable to get the geo data and report an error if something went wrong.

**Comment by mmguero** [comment]
Thanks, moved to idaholab/Malcolm#86
