### ISSUE TITLE
Opensearch crashes due to insufficient memory

### ISSUE THREAD

**Issue by RafnexJr** [cisagov/Malcolm#204]
# 🐛 Summary #

When following the default recommendation of the memory allocation the setup script provides and the system has no swap configured Opensearch repeatedly crashed because it can't allocate enough memory. Problems occured when the server has below 12 GB memory and now swap configured, it happend on Ubuntu, Debian and OpenSUSE.

## To reproduce ##

1. Server with 8GB memory and no swap
2. Install according to documentation
3. Start Malcolm with the script

## Expected behavior ##

The script should recommend less memory for Opensearch and Logstash when the system has below 12 GB memory and no swap.

## Any helpful log output or screenshots ##

The following output is shown (not exactly copied)

```console
OpenSearch exited with code 137
```

**Comment by mmguero** [comment]
Thanks, moved to idaholab/Malcolm#85
