### ISSUE TITLE
Docker pcap-monitor.Dockerfile opensearch-py dependancy bug

### ISSUE THREAD

**Issue by JonathanReifer** [cisagov/Malcolm#205]
Hello INL / CISA,
    First and foremost - fantastic project, thank you! Great project and solid documentation, its really appreciated!
     The issue I'm reporting is that when you build the system with the current version of opensearch-py that's utilized in the Dockerfiles/pcap-monitor.Dockerfile file it will fail to run.   This seems to be do to an upstream dependency issue with opensearch-py missing requests from its install_requires.  (appears to be a failure based on this: https://github.com/opensearch-project/opensearch-py/issues/141#issue-1177342587 )
 
Temp fix while we wait for the upstream library is to perhaps pin the opensearch-py version to an older one OR include requests in the Dockerfile:

pip3 install --no-cache-dir opensearch-py opensearch-dsl pyzmq       pyinotify python-magic **requests** && \

Thanks again for a great system!
jon

**Comment by mmguero** [comment]
Thanks!

**Comment by mmguero** [comment]
Will be fixed (via the workaround suggested) in 5.2.10.
