### ISSUE TITLE
auth_setup Permission Denied

### ISSUE THREAD

**Issue by Mattc1990** [cisagov/Malcolm#213]
# 🐛 Summary #

What's wrong? Please be specific.

After using the ./build.py I was trying use ./auth_setup to register the admin account but after I enter the name and password it comes back with a permission error. I was not using sudo and I verified I was on UID/GID of 1000. Not sure why I am getting this error.

##Reproduce##

1. ./auth_setup
2. Enter admin username and password
3. Get permission error

## Expected behavior ##

What did you expect to happen that didn't?

I expected to be able to create the admin account and move on to starting Malcolm

**Comment by mmguero** [comment]
Perhaps it's an issue of the ownership of the Malcolm-main directory itself?

Try this:

* `/home/waterskid/Malcolm-main/scripts/wipe`
* `sudo chown -R waterskid:waterskid /home/waterskid/Malcolm-main`
* `rm -f /home/waterskid/Malcolm-main/auth.env`
* `/home/waterskid/Malcolm-main/scripts/wipe`
* `/home/waterskid/Malcolm-main/scripts/auth_setup`

I've deleted the screenshot you attached as it contained a password, just to be safe.

**Comment by Mattc1990** [comment]
That seems to have worked. Thank you very much for the quick reply!
