### ISSUE TITLE
Docker Build Zeek returned a non-zero code:1

### ISSUE THREAD

**Issue by ErdemOzgen** [cisagov/Malcolm#215]
# 🐛 Summary #

What's wrong? Please be specific.

When we execute **docker-compose build** command we will face this error:
 ```
Errors were encountered while processing:
 ./libbroker-dev_5.0.0-0_amd64.deb
 ./zeek-btest-data_5.0.0-0_all.deb
 ./zeek-btest_5.0.0-0_all.deb
 ./zeek-client_5.0.0-0_all.deb
 ./zeek-core-dev_5.0.0-0_amd64.deb
 ./zeek-core_5.0.0-0_amd64.deb
 ./zeek-spicy-dev_5.0.0-0_amd64.deb
 ./zeek-zkg_5.0.0-0_all.deb
 ./zeek_5.0.0-0_amd64.deb
 ./zeekctl_5.0.0-0_amd64.deb
```
and returns a non-zero code: 1 and exits docker-compose.

## To reproduce ##

```bash
git clone https://github.com/cisagov/Malcolm.git
cd Malcolm
./scripts/build.sh 
# or you can call docker-compose build
```

## Expected behavior ##

What did you expect to happen that didn't?

Successful docker build.

## Any helpful log output or screenshots ##

![malcolmBug](https://user-images.githubusercontent.com/14043035/188151101-472b3e66-8870-4818-862b-f36de70c17cb.png)
Paste the results here:

```console


```

Add any screenshots of the problem here.
[error.txt](https://github.com/cisagov/Malcolm/files/9478043/error.txt)

**Comment by mmguero** [comment]
It's just due to the new Zeek release, I need to update the version once the new debs are out. I'm not going to be switching to the RC debs.
