### ISSUE TITLE
PCAP not accessible through arkime web interface

### ISSUE THREAD

**Issue by timberlakeis** [cisagov/Malcolm#219]
# 🐛 Summary #

What's wrong? Please be specific.

Packets are not displayed or exportable from arkime.

## To reproduce ##

1. Install arkime on ubuntu per instructions
2. upload pcap per instructions
3. view sessions in arkime
4. fail to load session. No error arises, just hangs indefinitely.

![image](https://user-images.githubusercontent.com/65873661/192665256-2a3a637e-acc4-4dd4-a5a1-cbb1897fa5e5.png)

5. Fail Download PCAP attempt

## Expected behavior ##

PCAP and PCAP segments should be downloadable

**Comment by mmguero** [comment]
I've retested this in the latest build and in the upcoming release builds. I'm unable to get it to break. If you'd like to share the log output from the docker containers when you reproduce this I'm happy to try to help diagnose it, but I don't think it's a general bug.
