### ISSUE TITLE
Filebeat certificate issues with .iso installer

### ISSUE THREAD

**Issue by Dleau** [cisagov/Malcolm#225]
# 🐛 Summary #

With the Malcolm installer from https://malcolm.fyi/docs/download.html, filebeat is having certificate issues and failing to process Zeek logs.

## To reproduce ##

1. Install Malcolm to a virtual disk using the version 6.4.3 .iso from the link above
2. Start Malcolm using scripts/start
3. Upload packet capture file via the web UI and elect to process with Zeek

## Expected behavior ##

The packet capture file is uploaded without issue and Zeek runs against the file without issue, as evident by the contents of zeek-logs/. However, filebeat fails to start due to certificate issues and cannot (to my understanding) ingest Zeek logs, send them to Logstash, etc. The error stanza below repeats indefinitely. 

## Any helpful log output or screenshots ##

Paste the results here:

```console

malcolm-filebeat-1            | 2022-12-28T16:50:48.077Z Setup Beat: filebeat; Version: 8.5.2
malcolm-filebeat-1            | 2022-12-28T16:50:48.088Z Failed reading certificate file /certs/client.crt: read /certs/client.crt: is a directory
malcolm-filebeat-1            | 2022-12-28T16:50:48.088Z Failed reading CA certificate: read /certs/ca.crt: is a directory
malcolm-filebeat-1            | 2022-12-28T16:50:48.088Z filebeat stopped.
malcolm-filebeat-1            | 2022-12-28T16:50:48.088Z Exiting: error initializing publisher: 2 errors: read /certs/client.crt: is a directory /certs/client.crt; read /certs/ca.crt: is a directory reading /certs/ca.crt
malcolm-filebeat-1            | Exiting: error initializing publisher: 2 errors: read /certs/client.crt: is a directory /certs/client.crt; read /certs/ca.crt: is a directory reading /certs/ca.crt
malcolm-filebeat-1            | 2022-12-28 16:50:48,101 INFO exited: filebeat (exit status 1; not expected)

```

**Comment by mmguero** [comment]
The startup script *should* have prompted you to create auth-related files (like those certs) the first time Malcolm started. I'll have to check and see if I can reproduce it not doing so. In the meantime, to clean up, open a terminal and do the following:

* `cd ~/Malcolm`
* `./scripts/wipe`
* `find ~/Malcolm -user root`, then delete all of the files/directories returned under `~/Malcolm` that were auto-created by the bind mounts of those missing files. You may have to use `sudo` to do that.
* `./scripts/auth_setup` this *should* generate the files under `./filebeat/certs`.
* `./scripts/start` to re-start Malcolm

**Comment by Dleau** [comment]
Thanks! That did the trick. Looking back, I believe I hit "n" for this prompt, where I should have hit "y".

`(Re)generate self-signed certificates for a remote log forwarder (Y/n): y`

**Comment by Dleau** [comment]
Although, this now seems to be a recurring issue.

`malcolm-logstash-1            | [2022-12-29T18:09:49,818][WARN ][org.logstash.plugins.pipeline.PipelineBus] Attempted to send event to 'zeek-parse' but that address was unavailable. Maybe the destination pipeline is down or stopping? Will Retry.`

Even with a fresh install from the .iso and a "y" answer to the prompt above (which fixes the certificate issues with logstash and filebeat), this problem persists :/

**Comment by Dleau** [comment]
All good! The zeek-parse pipeline took longer than expected to get its affairs in order.

**Comment by mmguero** [comment]
It can take several minutes for that pipeline to initialize. Glad we're sorted out.
