### ISSUE TITLE
Connection down when i start the malcolm

### ISSUE THREAD

**Issue by Briza0407** [cisagov/Malcolm#228]
Hi I'm installing Malcolm and when i initiate the command ./scripts/start, my VM connection is lost. Everytime I install VM and run the start command, my connection is lost.

Is there something that I can do?

**Comment by mmguero** [comment]
What are the resources on the VM and/or the host, and what do you have allocated to OpenSearch and Logstash? When this happens it's almost always because of insufficient system resources, usually memory.

**Comment by mmguero** [comment]
Still there?
