### ISSUE TITLE
zeek-live keeps crashing due to high memory usage

### ISSUE THREAD

**Issue by arasic** [cisagov/Malcolm#229]
# 🐛 Summary #

When starting all services with ./scripts/start, the service zeek-live keeps crashing due to high memory usage, causing the host system to be unstable.

## To reproduce ##

1. Configure zeek-live service by activating zeek live capture (ZEEK_LIVE_CAPTURE=true in docker-compose)
2. Start all services with `./scripts/start`

## Expected behavior ##

The expected behavior is that all services are up, running and zeek-live starts generating logs in ./zeek-logs directory where the full cycle of successful event processing results can be confirmed by identifying the events through Kibana or Arkime UIs.
`docker stats` should show stable memory usage, and not high fluctuation in RAM memory usage as described in the next section.
This screen capture shows when zeek-live service is running normally:
![Screenshot from 2023-01-16 11-32-31](https://user-images.githubusercontent.com/20152447/212726802-fdf06dbb-15c6-45eb-ae9d-01f1055e9b76.png)

## Any helpful log output or screenshots ##
When launching all services with zeek-live capture as turned on, the memory usage of the service zeek-live causes high fluctuation (i.e. **increases** of 2 to 4GB RAM per second,  **but also decrease** of 1 to 2GB RAM per second) until it reached little bit over 20GB of RAM causing the service zeek-live to crash, and restart, while at the same time causes the system to be unresponsive/unstable. This occurs a few times (4-5 times) and at the end, the zeek-live service dies.

## Other info ##
These observations were on OS Linux Fedora 37, with 47GB of RAM.
In my opinion, this seems to be related with configurations in zeek-live image (zeek plugins, intel, and/or the cron that is being used).
To make it work, I switched the image of the service zeek-live to activecm/zeek and simply configured the node.cfg and adjusted the volumes mapping:
```
  zeek-live:
    image: activecm/zeek
    restart: "no"
    stdin_open: false
    tty: true
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    environment:
      << : *process-variables
      << : *ssl-variables
      # << : *common-upload-variables
      # << : *zeek-variables
      # << : *zeek-live-variables
      # << : *pcap-capture-variables
      ZEEK_PCAP_PROCESSOR : 'false'
      ZEEK_CRON : 'false'
      ZEEK_LOG_PATH : '/zeek/live'
      #ZEEK_INTEL_PATH : '/opt/zeek/share/zeek/site/intel'
      EXTRACT_FILES_PATH : '/zeek/extract_files'
    volumes:
      # - ./nginx/ca-trust:/var/local/ca-trust:ro
      #- ./zeek-logs/live/logs:/usr/local/zeek/logs
      - ./zeek-logs/live/logs/current:/usr/local/zeek/spool/zeek
      - ./zeek-logs/extract_files:/zeek/extract_files
      - ./zeek/nodeconf/node.cfg:/usr/local/zeek/etc/node.cfg
      - ./zeek/config/local.zeek:/opt/zeek/share/zeek/site/local.zeek:ro
      - ./zeek/intel:/opt/zeek/share/zeek/site/intel
```
I am aware that  I am having many zeek plugins activated but it helps be able to try it.
Overall, this solution is awesome, great work team!

**Comment by mmguero** [comment]
Interesting. Just double checking, is the `PCAP_IFACE` value in the compose file what it should be? Are you using [zeek intel feeds](https://cisagov.github.io/Malcolm/docs/zeek-intel.html#ZeekIntel) at all? If so, are you setting `ZEEK_INTEL_FEED_SINCE` or other related variables? This isn't an issue I've seen before, just trying to brainstorm what it might be. What's the volume and makeup of the traffic on that interface you're capturing look like?

**Comment by arasic** [comment]
Sure, `PCAP_IFACE` is accurate, it points to the correct network interface.
The value for `ZEEK_INTEL_FEED_SINCE` is empty, so I think that I am not using any intelligence feeds.

I just realized that zeek-live was generating the following error before going to the fatal state: 
`Error: failed to update symlink '/zeek/live/logs/current': [Errno 21] Is a directory: '/zeek/live/logs/current'`

After deleting the directories inside `./zeek-logs/live`, and restarting zeek-live, the error was gone:
```
$ docker-compose up zeek-live
Starting malcolm_zeek-live_1 ... done
Attaching to malcolm_zeek-live_1
zeek-live_1           | usermod: no changes
zeek-live_1           | chown: changing ownership of '/opt/zeek/share/zeek/site/local.zeek': Read-only file system
zeek-live_1           | root
zeek-live_1           | uid=0(root) gid=0(root) groups=0(root)
zeek-live_1           | 2023-01-18 12:36:24,782 INFO Set uid to user 0 succeeded
zeek-live_1           | Unlinking stale socket /tmp/supervisor.sock
zeek-live_1           | 2023-01-18 12:36:25,087 INFO RPC interface 'supervisor' initialized
zeek-live_1           | 2023-01-18 12:36:25,087 CRIT Server 'unix_http_server' running without any HTTP authentication checking
zeek-live_1           | 2023-01-18 12:36:25,087 INFO supervisord started with pid 695
zeek-live_1           | 2023-01-18 12:36:26,090 INFO spawned: 'live-zeek' with pid 700
zeek-live_1           | Running via "/opt/zeek/bin/zeekctl"...
zeek-live_1           | checking configurations ...
zeek-live_1           | installing ...
zeek-live_1           | removing old policies in /zeek/live/spool/installed-scripts-do-not-touch/site ...
zeek-live_1           | removing old policies in /zeek/live/spool/installed-scripts-do-not-touch/auto ...
zeek-live_1           | creating policy directories ...
zeek-live_1           | installing site policies ...
zeek-live_1           | generating cluster-layout.zeek ...
zeek-live_1           | generating local-networks.zeek ...
zeek-live_1           | generating zeekctl-config.zeek ...
zeek-live_1           | generating zeekctl-config.sh ...
zeek-live_1           | stopping ...
zeek-live_1           | stopping worker ...
zeek-live_1           | creating crash report for previously crashed nodes: worker-1-1
zeek-live_1           | stopping proxy ...
zeek-live_1           | creating crash report for previously crashed nodes: proxy
zeek-live_1           | stopping manager ...
zeek-live_1           | creating crash report for previously crashed nodes: manager
zeek-live_1           | stopping logger ...
zeek-live_1           | creating crash report for previously crashed nodes: logger
zeek-live_1           | starting ...
zeek-live_1           | starting logger ...
zeek-live_1           | starting manager ...
zeek-live_1           | starting proxy ...
zeek-live_1           | starting worker ...
zeek-live_1           | 2023-01-18 12:39:26,233 INFO success: live-zeek entered RUNNING state, process has stayed up for > than 180 seconds (startsecs)
```

The container zeek-live still uses ~16GB of RAM, which I think is normal because its running in cluster mode.

**Comment by mmguero** [comment]
Interesting... I'll have to look at the startup script and see if I can catch some more of those kinds of things. Docker's automatic creation of directories for missing bind mounts has bitten me before and is kind of a pain IMO. Glad you figured it out.
