### ISSUE TITLE
Local Opensearch Instance Unreachable

### ISSUE THREAD

**Issue by Chappy59711** [cisagov/Malcolm#236]
# 🐛 Summary #

When Malcolm is started, an error indicating that http://opensearch:9200 is unreachable.

## To reproduce ##

1. I created a new Ubuntu 22.04 LTS Hyper V VM.
1. I followed the example from the Malcolm documentation.

## Expected behavior ##

What did you expect to happen that didn't?
A successful connection with the local opensearch database.

## Any helpful log output or screenshots ##
![image](https://user-images.githubusercontent.com/21272318/217616889-9d9c4b71-15b1-4bf3-b828-26cb30c98428.png)

**Comment by Chappy59711** [comment]
The websites do not work either.  I attached the log of the startup.

[tod.log](https://github.com/cisagov/Malcolm/files/10710758/tod.log)

**Comment by Chappy59711** [comment]
I found the issue.  The local firewall was blocking traffic and the networking was not correct.

**Comment by mmguero** [comment]
Glad you figured it out, and sorry for my delay in replying (I was on vacation last week).
