### ISSUE TITLE
Dashboards not loading

### ISSUE THREAD

**Issue by nilssachs** [cisagov/Malcolm#237]
Hey, hope you can support me.
I installed the current version of Malcolm and on the server itself, everything works fine.
As soon as I try to remotely connect to the OpenSearch and Arkime Dashboards, they are not loading anymore. Netbox is working.
Do you have any idea, what could be the issue?
Thanks in advance!

**Comment by mmguero** [comment]
Usually when services don't start up or aren't reachable it has to do with the resources available to the containers.

If you run `./scripts/status` from the Malcolm directory, what do you see? Are any of the containers showing as exited or not healthy in the `STATUS` column?

What are the resources (specifically available RAM) of the host? And how much memory allocated for Logstash and OpenSearch (`grep -Po "\w+_JAVA_OPTS.+Xm[sx]\w+" docker-compose*` will give you those figures)? Usually containers failing to stay started are dealing with limited resources.

Beyond that, maybe you can get it started up and into this state and then run `docker-compose logs > output.txt` and attach the contents of that file to this issue and I can try to make a better guess.

**Comment by nilssachs** [comment]
Thanks a lot for your quick response.
Status is healthy for all containers. 64GiB RAM installed.
```
OPENSEARCH_JAVA_OPTS : '-server -Xms30g -Xmx30g
LS_JAVA_OPTS : '-server -Xms6g -Xmx6g
```

What irritates me is, that the dashboards are working fine on localhost. Still trying to get an useful extract of the docker-compose logs.

**Comment by mmguero** [comment]
Ah, I missed the "remotely" from your original comment, my apologies. In that case, if they're working fine on localhost, I don't think the docker-compose commands are going to help us. 

Let's check and make sure the ports are forwarding as they should from docker. Run something like this, 

```
$ ./scripts/status | grep nginx
malcolm-nginx-proxy-1          malcolmnetsec/nginx-proxy:23.01.1         "/sbin/tini -- /usr/…"   nginx-proxy          3 weeks ago         Up 3 weeks (healthy)   0.0.0.0:443->443/tcp ...
```

You may see some other ports there at the end, but do you see `0.0.0.0:443->443/tcp` at least?

You don't have any other services on the machine that are already listening on 443/tcp, do you?

```
$ sudo netstat -anp | grep :443 | grep LISTEN
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      75451/docker-proxy  
```

What's the platform you're running this all on? Are you running this on your own Linux installation or is the whole OS installed via the [Malcolm installer ISO](https://cisagov.github.io/Malcolm/docs/malcolm-iso.html#ISO)?

If the things I've listed above don't give us an indication, then I'm guessing it's a firewall issue and not something I'd be able to help much with as it'd be external to Malcolm.
