### ISSUE TITLE
Idea: Terminate `./script/start` once Malcolm has started properly.

### ISSUE THREAD

**Issue by Njinx** [cisagov/Malcolm#240]
I find `./script/start` a bit clunky because you never really know when Malcolm is finished starting and able to be interacted with. Would you be open to changing the default behavior (or creating a setting) so that `./scripts/start` will terminate once Malcolm is fully started? I'd be happy to try and implement this myself, but I'd like to know if anybody is opposed to this beforehand.

**Comment by mmguero** [comment]
yeah that's a cool idea. "Fully started" could depend on your opinion of what that means, but generally for me I look for:

```
malcolm-logstash-1  | [2022-07-27T20:27:52,056][INFO ][logstash.agent           ] Pipelines running {:count=>6, :running_pipelines=>[:"malcolm-input", :"malcolm-output", :"malcolm-beats", :"malcolm-suricata", :"malcolm-enrichment", :"malcolm-zeek"], :non_running_pipelines=>[]}
```

The "Pipelines running" script from logstash is usually the last indication that Malcolm is fully ready to process data. 

You're welcome to take a stab at it, or I think I could take care of it this Friday once I get back from the travel I'm on.

Cheers

**Comment by mmguero** [comment]
Going into v23.03.0 release forthcoming
