### ISSUE TITLE
Is this gif supposed to do this?

### ISSUE THREAD

**Issue by tammynewbie** [cisagov/Malcolm#244]
![markup_16788416818554825604150232940888.gif (1).png](https://user-images.githubusercontent.com/88818955/225175753-bdb1f1ad-ebf9-4797-ac78-973a0987c5bd.png)

This Gif is small to transfer at first, but expands bigger, and has ability to share offline with any nearby device without permission, Yet incur data charges. 
@CISA
@DOD

I found it on DOD website.

**Comment by mmguero** [comment]
This repository is for issues dealing with the project Malcolm, the network traffic analysis tool suite, not specific network artifacts you might come across. Best of luck.

**Comment by tammynewbie** [comment]
Sorry, and thank you for the knowledge. I honestly appreciate it.
