### ISSUE TITLE
zeek detecting SFTP through script and not SFTP through applications like WinSCP and FileZilla

### ISSUE THREAD

**Issue by cyborg1234** [cisagov/Malcolm#245]
Hi,

Currently, I am testing the capability of zeek/arkime in one of my implementation.
I have tried file transfer through a custom-made dashboard which uses SFTP to transfer files from another computer, and zeek is able to detect the traffic and the traffic has protocol 'tcp ssl' and 'tcp tls'.

![image](https://user-images.githubusercontent.com/128014572/225534721-a85f64c5-d1e8-4b08-a643-6f5458828f45.png)
![image](https://user-images.githubusercontent.com/128014572/225534893-5388973b-bbe9-4e1b-9019-f3969ba3cfe2.png)

When I carried out file transfer using applications WinSCP and FileZilla to transfer files from the same computer, zeek/arkime is not able to detect it automatically, such that the traffic appears.

The traffic is observable using traffic detection application like Wireshark

![image](https://user-images.githubusercontent.com/128014572/225535227-db77bcdb-a20c-4911-bf54-fd9777b3e036.png)

The wireshark pcap file is then uploaded to Malcolm and the traffic gets detected by arkime with protocol 'ssh tcp'
![image](https://user-images.githubusercontent.com/128014572/225535828-557e034f-5dfb-4afb-9167-800ff2ad3adf.png)

When running wireshark for the file transfer using the custom-made dashboard, traffic captured are of tls, as compared to the previous wireshark screenshot whereby the protocol is ssh for file transfer using file transfer applications.
![image](https://user-images.githubusercontent.com/128014572/225536146-dcef03cf-95c8-400c-a4d4-66ac8b85a5d8.png)

My guess is that arkime on my system is currently not detecting the traffic with protocol 'ssh tcp' automatically.

Would tinkering with zeek or arkime backend in terms of the way it detects traffic allows the file transfer using file transfer applications be detected? And how do I go about doing the tinkering?

Thank you.

**Comment by mmguero** [comment]
Interesting. We're not doing anything specific outside of what Zeek and Arkime normally do for SSH traffic (Zeek [here](https://docs.zeek.org/en/master/scripts/base/protocols/ssh/main.zeek.html), Arkime [here](https://github.com/arkime/arkime/blob/main/capture/parsers/ssh.c)). I can see in your screenshots that sometimes different ports are being used (22 vs. various high ports I see in your destination port column there in arkime). Could it be that Zeek and/or Arkime are limiting SSH detection to particular ports?

One thing that is also important to note for Malcolm, at least, when using Malcolm to do live capture Zeek logs are "tailed" and processed immediately, while Arkime capture happens on a 10-minute rotating schedule.

**Comment by e101sg** [comment]
Just another thought to add from the Operating System context.

1) I assume OS is Windows 10 /11 is running on both computers (server /client)?  Since the Zeek is not natively supported on Windows OS (yet), it may miss when non-standard ports are used for SFTP. 

2) have u checked the Zeek logs, just after the file transfer was completed? believe it should be recorded either in the conn.log or ssh.log /weired.log.

**Comment by mmguero** [comment]
As far as I can tell, Zeek is doing what it should for these protocols.
