### ISSUE TITLE
install.py bug

### ISSUE THREAD

**Issue by JJKLab** [cisagov/Malcolm#252]
/scripts/install.py
  File "./scripts/install.py", line 2728
    (orchMode := DetermineYamlFileFormat(args.configFile)) and (orchMode in OrchestrationFrameworksSupported)
              ^
SyntaxError: invalid syntax

**Comment by mmguero** [comment]
What's your python version? My guess is the syntax it's complaining about is the [assignment expression](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions) or "walrus operator" which was introduced in Python 3.8. If you're running an older version of python on your system, you could look into [pyenv](https://github.com/pyenv/pyenv) or [asdf](https://asdf-vm.com/) to run a more up-to-date Python for Malcolm.

**Comment by mmguero** [comment]
Hopefully that addresses your issue. I think running Python v3.8 will address your problem.
