### ISSUE TITLE
install.py can create .env files 0:0 ownership instead of unprivileged user ownership

### ISSUE THREAD

**Issue by e101sg** [cisagov/Malcolm#253]
# Got the installation issue on Ubuntu while installing v23.05.0 #

After running the  `auth_setup,docker pull`, get an issue when  running .`/scripts/start`. The issue is permission error.
PermissionError: [Error 1] Operation not permitted : 'pcap-capture.env '
I have tried to build from scratch as well..got some Logstash related error at the end (almost) of the build. Not sure, this issue related to new release (23.05.0). Any thoughts highly useful.. (spend the whole weekend for this) ~ Cheers!

![Screenshot from 2023-05-14 22-13-36](https://github.com/cisagov/Malcolm/assets/1925934/3596bd56-2737-4b52-9077-a6a56ef74c7c)

**Comment by mmguero** [comment]
Hmmm, looks like somehow there's a scenario where part of the `install.py` portion which runs as root populated the `.env` files which ended up in the file ownership not being set correctly for non-root users. I'll look into and see if I can replicate.

In the meantime, doing something like this should solve the problem:

```bash
$ cd ~/Documents/Malcolm
$ ./scripts/wipe
$ sudo chown -R user:user ~/Documents/Malcolm
$ ./scripts/wipe
$ ./scripts/start
```

1. cd into the Malcolm directory
2. stop/clean everything out with the `wipe` command
3. change ownership of that directory to your `user` account
4. clean everything out again after the chown command just for good measure
5. start malcolm back up again

**Comment by e101sg** [comment]
yes, this solves the permission issue and Malcolm stated. However, none of the dashboard (Malcolm services on browser) comping up in the browser even after 5 min.  Not sure why? i have run the above comments only.  ( did not run the from the beginning  ie.  `sudo ./scripts/install.py_`). Thanks.

![malcolm_wipe](https://github.com/cisagov/Malcolm/assets/1925934/6df0caff-2c6b-4bb3-9fb1-7ae662a20992)

**Comment by mmguero** [comment]
Run `./scripts/status` or `docker-compose ps -a` in your Malcolm directory and let me see the output.

**Comment by e101sg** [comment]
Sure. Here it is...

![Screenshot from 2023-05-16 08-44-12](https://github.com/cisagov/Malcolm/assets/1925934/9e8c14e0-d1b4-4867-9e8c-199500a04cef)

**Comment by mmguero** [comment]
My guess is now you're looking at resources (memory) issues for opensearch. What's the system memory (`head /proc/meminfo`) and what do you have allocated for OpenSearch and LogStash (`grep JAVA_OPTS ./config/*.env`)?

**Comment by e101sg** [comment]
Memory should not be issue since the machine is Desktop with 32GB memory. Screen shot.

![Screenshot from 2023-05-16 20-37-03](https://github.com/cisagov/Malcolm/assets/1925934/f8416924-10c1-4d01-8f46-9e4d42d6cef9)

Interestingly, when i try to stop the Malcolm, getting some strange error.. _(seeing it first time)_
Hope it gives a hint.. what is an issue. 

![stop_error](https://github.com/cisagov/Malcolm/assets/1925934/10fe26b9-d201-4c23-a5c1-b003818689e5)

**Comment by mmguero** [comment]
I'd double-check and just make sure (while malcolm is shut down) all files in `~/Documents/Malcolm` are owned by your user (`sudo chown -R user:user ~/Documents/Malcolm`).

As far as the `permission denied` goes, I've only seen that [one other place](https://github.com/idaholab/Malcolm/issues/167#issuecomment-1485922904), it was when a user was running "Ubuntu Core" which (I guess) is an all snap-based Ubuntu distro. That's not what you're using by chance, is it? I was never able to figure out his problem.

**Comment by mmguero** [comment]
Closing this issue as its initial root cause (the permission of the .env files) has been fixed and released in Malcolm v23.05.1.

**Comment by e101sg** [comment]
Update: Able to see dashboards after successful installation.  Thanks a lot for timely help. :)  Cheers!

**Comment by mmguero** [comment]
Glad to hear it!
