### ISSUE TITLE
Start Script Changing Permissions

### ISSUE THREAD

**Issue by redbaroncon86** [cisagov/Malcolm#259]
I am testing out Malcolm for possible usage.  I am following the setup here to my test install:  https://github.com/cisagov/Malcolm/blob/main/docs/ubuntu-install-example.md#InstallationExample.

The system is virtual machine running Ubuntu 22.04 with 4 CPU cores and 16 GB or RAM.  It has a static IP address running on on a bridged port.

The install seems to go great (reference pictures 1,2) until I run the start script.  My initial run changes permissions on the opensearch directory from the current user and stops (pictures 3,4).  I can take ownership back and it seems to run (picture 5).  However, when I attempt to go to Arkime and opensearch I get 502 Bad Gateway error (picture 6).  I am able to get to the upload and auth pages, however.  I also noted a change in the permissions (picture 7).

Any assistance or insight you can provide is apprecaited.

![1-Install_Results](https://github.com/cisagov/Malcolm/assets/28735703/9dda135d-aa31-4928-bfb1-7a6b6e8f853f)
![2-DockerImages](https://github.com/cisagov/Malcolm/assets/28735703/a1d2ddab-522c-4b66-b002-ef8babed8774)
![3-ScriptStart](https://github.com/cisagov/Malcolm/assets/28735703/d7a91e84-2980-4bec-bb4c-cbba03ce976a)
![4-NewPermissions](https://github.com/cisagov/Malcolm/assets/28735703/ad9e0e3d-4f67-4e8c-b5e6-5d8b998fcaaa)
![5-ScriptStart_RunAfterCHOWN](https://github.com/cisagov/Malcolm/assets/28735703/49405c2b-75d4-4542-9efc-768bf487e5f0)
![6-Arkime](https://github.com/cisagov/Malcolm/assets/28735703/9d7f23c6-b176-4ca6-8544-f364bdbe6b80)
![7-NewPermissions](https://github.com/cisagov/Malcolm/assets/28735703/26a78387-fef3-4297-93d7-513e9c089abc)

**Comment by mmguero** [comment]
My guess is the `PUID` and `PGID` environment variables were not set correctly during the configuration questions (`Malcolm processes will run as UID 1000 and GID 1000. Is this OK? (Y/n)`).

You'll likely be able to get things right again by doing:

1. `./scripts/wipe` to stop things and clear what you can out
2. `sudo chown -R cnorton:cnorton /opt/Malcolm` to recursively set permissions for the Malcolm directory to your user
3. `id -u` and `id -g` to get your actual user's UID and GID
5. edit `config/process.env` and fix the `PUID` and `PGID` values
6. `./scripts/wipe` to clear out what we couldn't clear out before

**Comment by redbaroncon86** [comment]
The ./scripts/wipe didn't seem to so I reloaded from a snapshot and restarted the Malcolm installation.  Replacing the default values with the non-root UID and GID did the trick.

Thanks for the quick reply and the assistance!
