### ISSUE TITLE
iso installation failed

### ISSUE THREAD

**Issue by gondmhd** [cisagov/Malcolm#260]
malcolm-23.05.1.iso
The version image is installed on the dell server, and it will always be stuck in the installation system step, prompting failure, unable to run normally and live installation
Tips are as follows
[!!] Install the system f
Installat ion step failedAn installation step failed. You can try to run the failing item again from the menu, or skip it and choose something else. The failing step is: Install the system  
<Continue>
sctiivates buttons

**Comment by mmguero** [comment]
That is not really enough information for me to give you any sort of ideas as to what might be failing.

I suppose you could try following some of the steps for debugging the debian installer (see [here](https://www.debian.org/releases/stable/i386/ch05s04)), particularly those regarding looking at syslog and/or dmesg.
