### ISSUE TITLE
Arkime Session Dropdown Not Displaying PCAP Data

### ISSUE THREAD

**Issue by ean8742** [cisagov/Malcolm#262]
# 🐛 Summary #

When opening the Arkime session view and clicking the dropdown, the packet payload information/section is missing underneath the metadata section.  I also only have the Link and Actions buttons available when expanding a session, and am missing Download PCAP, Source Raw, and Destination Raw. I'm currently running Malcolm 23.04.0 on Ubuntu 22.04, installed from the tar.gz file. Any help would be greatly appreciated!

## To reproduce ##

1. Open Arkime at localhost
2. Click on Sessions view
3. Dropdown session using + button
4. Metadata is only available (ex. HTTP, Zeek Common Fields, etc.) I cannot see packet payload data

## Expected behavior ##

Arkime should have a packet section in the session dropdown that displays payload information, allows you to show images and files, show info, etc. 

Please see video [link](https://www.youtube.com/watch?v=4tkho3OSzdo&t=3930s&ab_channel=MalcolmNetworkTrafficAnalysisToolSuite) for visual reference - Timestamp: 1:05:20

**Comment by mmguero** [comment]
The packet stuff is available for Arkime session record types. Malcolm also displays Zeek logs and Suricata alerts in Malcolm, which, of course, don't have associated PCAP. Are you sure the session you're looking at is an arkime session and not one of the other types? The second and third columns in the sessions table show the data source provider (e.g., arkime, zeek, suricata) and the log type (e.g., session, conn, alert). See around timestamp 1:22:35 in that same video.

**Comment by ean8742** [comment]
I appreciate the quick reply! As predicted, I wasn't looking at the right session type. Thank you for your help!
