### ISSUE TITLE
Unable to get iso from vagrant build script

### ISSUE THREAD

**Issue by grumo35** [cisagov/Malcolm#263]
Hi,

I want to build the malcolm iso using https://github.com/cisagov/Malcolm/blob/main/malcolm-iso/build_via_vagrant.sh

according to the documentation https://cisagov.github.io/Malcolm/docs/malcolm-iso.html#ISOBuild

Steps i did

1. Clone repository, get vagrant plugins
2. ./build_via_vagrant.sh -f

The VM is correctly build using Virtualbox provider, but i donthave any malcolm*.iso, almost like no references in the script ? 

Am i missing something ? 

Thanks.

**Comment by mmguero** [comment]
Does it go through the entire build process (~45-60 minutes)? What output do you have on the command line? Is a .log file created?

**Comment by mmguero** [comment]
ping?
