### ISSUE TITLE
support PCAP files with 802.11 packet structure

### ISSUE THREAD

**Issue by cwilliams001** [cisagov/Malcolm#264]
To reproduce

Convert a PCAPNG file to PCAP using tshark with the following command:

```
tshark -F pcap -r {input.pcapng} -w {output.pcap}
```

Attempt to upload the resulting PCAP file to Malcolm.
Expected behavior
I expected Malcolm to be able to read and analyze the PCAP file converted from PCAPNG.

I am trying to convert pcapng files from a kismet capture into pcaps so that I can use Malcolm as a data visualization tool and to do more in-depth analysis. Thank you!

[EDIT]

I reached out to the developer of Arkime and the issue is that Arkime does not support 802.11 packets.

**Comment by mmguero** [comment]
Thanks for the update. Will keep that in mind for future development.

**Comment by mmguero** [comment]
migrated to  idaholab/Malcolm#220
