### ISSUE TITLE
PCAP File with no `-` in pcapng Fails to Upload

### ISSUE THREAD

**Issue by jaredthecoder** [cisagov/Malcolm#265]
Hi team!

The line below causes PCAPNG files with the file type `(application/octet-stream/pcapng capture file - version 1.0)` to fail on upload with the following message: `pcap-monitor_1        | 2023-07-06 18:08:37 WARNING: watch-pcap-uploads-folder.py:	����	/pcap/upload/AUTOSURICATA,AUTOZEEK,AUTOCARVEall,sourcehttpsgithub.comEmreEkinICS-Pcaps,USERTAG,TheUltimate.pcap (application/octet-stream/pcapng capture file - version 1.0)`

This PCAP is an open source one from https://www.netresec.com/?page=PcapFiles.

The issue is the `if` check looks for `pcap-ng` exclusively and not also `pcapng`.

On top of this, the warning is not apparent to the real issue and without looking at the source code, appears as if the upload silently fails. My terminal also is not rendering the Unicode characters (I am SSH'd in to a server that doesn't have it setup).

- https://github.com/cisagov/Malcolm/blob/c4942d85657cdc77f92e089cebca91cda76d8d6b/pcap-monitor/scripts/watch-pcap-uploads-folder.py#L61

**Comment by mmguero** [comment]
Thanks, I've adjusted the code to be more flexible in how it recognizes those file types. It will be included in the next Malcolm release.

FWIW, Malcolm only has partial support for PCAP-NG files, as [Arkime doesn't support it](https://arkime.com/faq#how-do-i-import-existing-pcaps) very well. Your best bet is to convert to PCAP format first.
