### ISSUE TITLE
Misleading Documentation on PCAP_PIPELINE_VERBOSITY silently crashes PCAP-Monitor, Zeek, and Suricata on Docker

### ISSUE THREAD

**Issue by jaredthecoder** [cisagov/Malcolm#266]
# 🐛 Summary #

Specifying the verbosity as `vvv` in upload-common.env for `PCAP_PIPELINE_VERBOSITY` as shown in the comment string above it crashes the `pcap-monitor`, `zeek`, and `suricata` Docker containers with a repeated usage (CLI) message eventually crashing b/c of too many restarts.

I was changing this to debug some issues with SFTPing PCAPs up to the pcap-upload server.

## To reproduce ##

1. Specify `vvv` in [upload-common.env](https://github.com/cisagov/Malcolm/blob/main/config/upload-common.env.example#L8), instead of a number as it expects but isn't documented in the config file.
2. Restart Malcolm.
3. Observe the continuous crashing of the `pcap-monitor`, `zeek`, and `suricata` services, since all of them reference the same `PCAP_PIPELINE_VERBOSITY` variable in the Docker entrypoints.

## Expected behavior ##

I expected that `vvv` would work per the comment string, but also noticed that the usage help string shows `-vv` and not `-vvv`. See https://github.com/cisagov/Malcolm/blob/c4942d85657cdc77f92e089cebca91cda76d8d6b/pcap-monitor/scripts/watch-pcap-uploads-folder.py#L106.

Just cleaning up the docs would help here. I am participating in GeekWeek8 with CCCS (Canada) on behalf of my company ([SecurityScorecard](https://securityscorecard.com)), and will put together a broader PR towards the end of this week with additional docs and some improvements that we've learned while setting Malcolm up to capture remotely from a large ICS testbed. Thanks so much for all the hard work!

## Any helpful log output or screenshots ##

Example of it crashing: 
![Screenshot 2023-07-11 at 12 21 01](https://github.com/cisagov/Malcolm/assets/7459310/69568da0-47ed-4726-9bd4-a1e7591bc2cd)

**Comment by mmguero** [comment]
In your bug summary you list `vvv`, when the instructions and comments indicate you need to put a dash (e.g., `-vvv`). It's not crashing, it's indicating that you've specified the incorrect format for that debug option. Does it work the way you expect if you put the dash before the option?

**Comment by mmguero** [comment]
Working as intended (note the dash, `-vvv`)

```
$ grep PCAP_PIPELINE_VERBOSITY config/upload-common.env
PCAP_PIPELINE_VERBOSITY=-vvv
```

Then, start Malcolm:

```
./scripts/start
```

Then after the containers have started up:

```
$ ps axf | grep vvv | grep -v grep
 192999 pts/0    Sl     0:00                      \_ python3 /opt/pcap_arkime_processor.py -vvv --start-sleep 10 --threads 1 --publisher pcap-monitor --pcap-directory /data/pcap/processed --node seven --arkime /opt/arkime/bin/capture --autotag true --managed true
 191917 pts/0    S      0:00                      \_ python3 /usr/local/bin/pcap_watcher.py -vvv --opensearch http://opensearch:9200 --opensearch-curlrc /var/local/curlrc/.opensearch.primary.curlrc --opensearch-ssl-verify false --opensearch-wait --node seven --ignore-existing false --polling false --closed-sec 10 --start-sleep 60 --directory /pcap/processed
 191918 pts/0    S      0:00                      \_ python3 /usr/local/bin/watch-pcap-uploads-folder.py -vvv --start-sleep 30 --polling false --closed-sec 10 --in /pcap/upload --out /pcap/processed --zeek /zeek/upload --uid 1001 --gid 1001
 193437 pts/0    S      0:00                      \_ python3 /usr/local/bin/filebeat-watch-zeeklogs-uploads-folder.py -vvv --start-sleep 30 --polling false --closed-sec 10 --in /zeek//upload --out /zeek/ --uid 1001 --gid 1001
```

Notice the `-vvv` was passed to the commands, and I'm not getting the message about incorrect usage.

**Comment by jaredthecoder** [comment]
@mmguero I see that now, and it is working if you pass that. The issue @mmguero is that the documentation is confusing and is what led to this in the first place. We have an INL employee and Malcolm contributor here at the event at CCCS that couldn't figure the issue out from the logs, so I spent a couple more hours digging into unrelated containers thinking it wasn't the configuration. :( 

In one part of the configuration specifications verbosity is specified by a number as well versus `v` or `-v`. 

I can make a PR with updated docs if that is easiest for you?
