### ISSUE TITLE
Can't Get Docker Compose to Pull

### ISSUE THREAD

**Issue by skullswalk** [cisagov/Malcolm#27]
I run the docker compose cmd in the malcolm directory (utilizing the github repo) and I get the following error:
`ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/`

When that failed I went ahead and just commented out the version in the docker-compose.yml file and ran the pull again and got this error:

`ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for x-common-upload-variables: 'AUTO_TAG'
Unsupported config option for x-common-beats-variables: 'BEATS_SSL'
Unsupported config option for x-logstash-variables: 'ES_EXTERNAL_SSL_CERTIFICATE_VERIFICATION'
Unsupported config option for x-zeek-file-extraction-variables: 'EXTRACTED_FILE_START_SLEEP'
Unsupported config option for x-moloch-variables: 'INITIALIZEDB'
Unsupported config option for x-kibana-variables: 'KIBANA_OFFLINE_REGION_MAPS'
Unsupported config option for x-pcap-capture-variables: 'PCAP_FILTER'
Unsupported config option for services: 'moloch'`

Please help!

**Comment by mmguero** [comment]
Looks to me like a version incompatibility between the docker-compose.yml format and your version of Docker compose. What do you get when you run the following few commands?

`docker-compose version`

`which docker-compose`

**Comment by skullswalk** [comment]
I kind of had that feeling too, but I just wanted to run everything by you first before I started rolling back.

```
$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15+
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

$ which docker-compose
/usr/bin/docker-compose

**Comment by mmguero** [comment]
So [1.17.1](https://github.com/docker/compose/releases/tag/1.17.1) is about a year and a half old, it would appear. There are some docker-compose.yml syntax features I'm using that weren't supported at that time. I'd recommend [updating docker-compose to a newer version](https://docs.docker.com/compose/install/) and see if that helps.

**Comment by skullswalk** [comment]
Ahh I was about to go the wrong way, so upgrading the docker-compose version did the trick. Thank you for all the help!!
