### ISSUE TITLE
How to do an automatic installation?

### ISSUE THREAD

**Issue by telekomancer** [cisagov/Malcolm#273]
# 💡 Summary #

Automate installation

## Motivation and context ##

How do we fully automate the installation from source code

git clone ...Malcom
Malcolm/scripts/install.py --automatic ??

## Implementation notes ##

For example if i want to use my own and custom linux version and only automate the malcolm installation from cloning the repo and simply "docker compose up"

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Simply run `docker compose up -d`

And everything work

**Comment by mmguero** [comment]
Thanks for the issue. Right now there are a few "non-automated" parts to the Malcolm setup we'd have to consider:

* the system-level configuration stuff in `./scripts/install.py` (run as superuser)
    * this includes changing system settings in /etc/sysctl.conf, file handle limits in /etc/security/limits.conf, setting recommended kernel parameters for grub for best performance, etc. This may or may not be something you want to have done automatically.
* the malcolm-specific [configuration stuff](https://idaholab.github.io/Malcolm/docs/malcolm-config.html#ConfigAndTuning) in `./scripts/install.py` (not needed as superuser)
    * the questions asked in this wizard modify a bunch of environment variables. There actually is an "accept defaults" mode but it doesn't have flags for all of the questions, so I'd need to modify the script to allow you to specify the answer to every single configuration flag at the command line, because what's enabled for one user might not be the same as what's enabled for another user
* the [authentication-related stuff](https://idaholab.github.io/Malcolm/docs/authsetup.html#AuthSetup)
    * generating self-signed certificates and setting up the username/passwords. I'm not sure how we'd handle the passwords stuff, you wouldn't really want to pass it on the command line I think.

It's a great suggestion, thanks. I think we can make it work. I'm going to move this issue over to the idaholab/Malcolm fork which is where I do issue tracking for the project and track it there.

**Comment by mmguero** [comment]
moved to idaholab/Malcolm#237
