### ISSUE TITLE
Hedgehog Linux SD card image for Raspberry Pi

### ISSUE THREAD

**Issue by furrnace** [cisagov/Malcolm#277]
# 💡 Summary #

Is there or will there ever by a Hedgehog Linux image for Raspberry Pi (4b) SD card?

## Motivation and context ##

When I first looked at Malcolm I thought I had seen an SD card image of Hedgehog Linux for Raspberry Pi, but later I was unable to find it again.

Still I am wondering if the RPi 4b is sufficiently powerful to run reasonable run Hedgehog Linux tools and if there will be an SD card image. This would make deployment in the field for small networks (or home labs) so much more convenient.

## Implementation notes ##

I believe the idea is self-explenatory from what is written above. If more input is needed, ask in this thread.

## Acceptance criteria ##

A Hedgehog VM deployment is fully interchangeable with a physical Hedgehog deployment on an SD card for Raspberry Pi 4b.

**Comment by mmguero** [comment]
Thank you for the request! We have not had a Pi deployment image yet, but we like the idea. I'm going to move this issue to the fork where we track project development issues and @ you there.

**Comment by mmguero** [comment]
Moved to idaholab/Malcolm#250, closing as duplicate
