### ISSUE TITLE
Upload upload issue 

### ISSUE THREAD

**Issue by gondmhd** [cisagov/Malcolm#280]
# 🐛 Summary #
1、Unable to upload pcap package
2、The uploaded zip file is not parsed
What's wrong? Please be specific.
Deploying Malcolm using k8s for v23.08.1 deployment. After deployment, it was found that the PCAP file cannot be directly uploaded. Compressing the PCAP file into a zip file can be uploaded, and the compressed file can be viewed in the container, but it has not been parsed
## To reproduce ##
![image](https://github.com/cisagov/Malcolm/assets/127921715/215a64e8-ece4-4277-85f3-5f1e243c266f)
![image](https://github.com/cisagov/Malcolm/assets/127921715/5750fb45-2d41-4e99-a2eb-ff038ced8597)

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by mmguero** [comment]
Malcolm has not supported uploading compressed PCAP files. The archives that are imported are expected to contain zeek logs (see the [documentation](https://cisagov.github.io/Malcolm/docs/upload.html#Upload)).

Creating idaholab/Malcolm#268 to track the enhancement request.
