### ISSUE TITLE
Moloch Packet capture fall behind

### ISSUE THREAD

**Issue by Maiseyjon** [cisagov/Malcolm#48]
I have setup Malcolm in a test lab on my home server, I seem to be having a perpetual issue with the moloch pcap being around 12hours behind the Zeek events. I installed following the Ubuntu install guide. I have looked into disk/performance issues and don't see anything specific but would like to get some thoughts if possible

**Comment by mmguero** [comment]
That is very strange, I've never seen that before. Do you mean that the date/times on the moloch sessions are exactly 12 hours behind the zeek events, but they all more or less show up in the GUI at the same time (indicating maybe some kind of time zone issue)? Or do you mean you literally wait 12 hours before the processing is done?

The `moloch-capture` process which ingests the PCAP for creating moloch session records executes before the PCAP even gets passed to Zeek for processing, let alone ingestion with Logstash. At the point the Zeek stuff happens the moloch stuff should already be done.

You could watch the debug output of the docker containers. When you upload your PCAP, you will see a message from the moloch container where the PCAP is moved from the upload directory to the processing directory. Then a minute later you'll see elasticsearch mention that it's created a sessions2 index for that PCAP. Later you'll see filebeat grab the zeek logs and harvest them.

If you'd like to clear out your database (`./scripts/wipe.sh`), then start it up again and upload a single PCAP, then save off the docker-compose logs (`docker-compose logs > output.txt` or something like that) and upload that here I can try to make a guess as to what's going on.

**Comment by Maiseyjon** [comment]
Sorry I may not have been clear.

So Zeek and Moloch are both processing, however the moloch pcap seem to be falling behind i.e i can see current Zeek logs and packets from ~12 hours ago. 

This is based on a live capture as opposed to manual upload however will follow your steps.

Cheers!

**Comment by mmguero** [comment]
Could it be a resources issue? How much RAM's on the system? How much have you got allocated to Elasticsearch and Logstash?

```
$ grep JAVA_OPTS docker-compose.yml
      ES_JAVA_OPTS : '-Xms21g -Xmx21g -Xss256k -Djava.security.egd=file:/dev/./urandom'
      LS_JAVA_OPTS : '-Xms3500m -Xmx3500m -Djava.security.egd=file:/dev/./urandom'
```

What numbers do you have for Xms and Xmx on those two lines?

**Comment by Maiseyjon** [comment]
so I had 20g and 3g respectively, I took a look through and decided to rebuild and set some of the indicies to expire sooner (store only 5-10 days).

In terms of the xms and xmx I believe they were the standard values, will try to confirm.

Will update once rebuild is complete.

**Comment by Maiseyjon** [comment]
So after a rebuild it looks to be stable and accurate, what i do know is that i had over 1.5m pcap files within the relevant folders. I think as you suggested the likely issue was ES utilising too much memory and not allowing the pcap to be processed efficiently. I may do some further testing on this to see where the breakpoints are but happy to close out as it was likely a config issue my side.
