### ISSUE TITLE
Forward Logstash logs to a secondary remote document store

### ISSUE THREAD

**Issue by devilman85** [cisagov/Malcolm#497]
to the question... Forward Logstash logs to a secondary remote document store? (y / N): y

Having a cluster with 3 data elastic serach nodes and a logstash machine, do I forward the data to my logstash?

**Comment by mmguero** [comment]
No, this is for forwarding to a secondary remote elasticsearch instance in addition to Malcolm's primary opensearch/elasticsearch instance. The logs go through Malcolm's logstash pipeline prior to forwarding.
