### ISSUE TITLE
Issue regarding installation of netbox

### ISSUE THREAD

**Issue by S1ubb** [cisagov/Malcolm#503]
I encounter a problem when trying to install netbox, it can't get the packages randomcolor and malcolm_utils.

To Reproduce
in your malcolm repository, go to /netbox/scripts/
Run the ./netbox_init.py
see the error of a few packages not wanting to be installed, install them
find out 2 packages are not available, those being randomcolor and malcolm_utils

Malcolm config
-- via the docker on linux (debian)

**Comment by mmguero** [comment]
That script isn't to be run by the user, it's only run internally and programatically in the NetBox container.

To enable netbox, you do so during [Malcolm configuration](https://cisagov.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#MalcolmConfig), by answering **Y** to **Should Malcolm run and maintain an instance of NetBox, an infrastructure resource modeling tool?**
