### ISSUE TITLE
The Suricata alert did not appear on the dashboard

### ISSUE THREAD

**Issue by alleniverson33** [cisagov/Malcolm#507]
malcolm 23.08.1    k8s

![Image](https://github.com/user-attachments/assets/ccb1fdef-11f3-4f23-b928-2b14982a4158)

The data is available in the parsed evejson file of Suricata, but it is not displayed in the dashboard or opensearch. (Filebeat, Logstash components are running normally)

May I ask how to troubleshoot such issues

**Comment by mmguero** [comment]
So other logs (like Zeek logs) are displaying on the dashboards, but Suricata isn't, is that correct? Can we make sure that your search time frame is covering the entire possible time range? (I wouldn't imagine with running in K8s that the time frame on the captured PCAP and what your browser is set to but it's something to check). So, in other words, setting your search time frame in dashboards as "one year ago" to "1 day from now" or something like that? 

Is this from uploaded PCAP data or live-captured network traffic?

Something else we could do is look at the filebeat container logs:

```
./scripts/logs -s filebeat | grep eve
```

And see what comes from those messages.

**Comment by alleniverson33** [comment]
> So other logs (like Zeek logs) are displaying on the dashboards, but Suricata isn't, is that correct? Can we make sure that your search time frame is covering the entire possible time range? (I wouldn't imagine with running in K8s that the time frame on the captured PCAP and what your browser is set to but it's something to check). So, in other words, setting your search time frame in dashboards as "one year ago" to "1 day from now" or something like that?
> 
> Is this from uploaded PCAP data or live-captured network traffic?
> 
> Something else we could do is look at the filebeat container logs:
> 
> ```
> ./scripts/logs -s filebeat | grep eve
> ```
> 
> And see what comes from those messages.

The alarm data for restarting the logstha component Suricata can be seen on the dashboard

**Comment by mmguero** [comment]
I don't understand your reply. Is this different than the other issue you logged? I don't even understand your issue here, you have not given any useful details or actionable information.
