### ISSUE TITLE
Could  Malcolm identify and display operating systems?

### ISSUE THREAD

**Issue by meetpity** [cisagov/Malcolm#535]
1、I would like to know if Malcolm provides a way to query the operating system of devices. I noticed that IP addresses and hostnames are displayed, but I couldn’t find any corresponding information related to operating systems.

2、When I open the OpenSearch Dashboard overview, the DNS requests section is empty and does not display any information. However, if I select a longer time range, such as 2 hours, the DNS request statistics appear. Could this indicate an issue somewhere?

Looking forward to your response.

**Comment by mmguero** [comment]
I'm converting this issue to a discussion, let's continue the conversation there.
