### ISSUE TITLE
investigate open distro for elasticsearch

### ISSUE THREAD

**Issue by mmguero** [cisagov/Malcolm#70]
https://opendistro.github.io/for-elasticsearch/

This looks like it might be a good choice for the default ES images used for Malcolm

**Comment by mosajjal** [comment]
This could potentially cover what ElastAlert does as well. OpenDistro comes with free Alerting plugin for Kibana!

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [idaholab/Malcolm](https://github.com/idaholab/Malcolm/issues/15)
